config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # get "home", to: "pages#home"
  root to: "pages#home"
  get "/about", to: "pages#about"
  get "/browse", to: "browses#browse", as: :browse
  # Defines the root path route ("/")
  # root "articles#index"

  post "/matches/update_or_create", to: "matches#update_or_create", as: :update_or_create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :user1, class_name: "User"
  belongs_to :user2, class_name: "User"

  enum status: { pending: "pending", matched: "matched", canceled: "canceled" }

  after_save :update_status

  def update_status
    if user1_accepted && user2_accepted
      self.status = :matched
    end

    save if changed?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many_attached :photos

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, photos: []])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username, photos: []])
  end
end

app/controllers/browses_controller.rb
class BrowsesController < ApplicationController

  def browse
    @users = User.where.not(id: current_user)
  end

  def like
    # swipe right
  end

  def dislike
    #swipe left
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:update_or_create]

  def update_or_create
    p params
    match = Match.find_by(user1_id: params[:user_to_match_id], user2_id: params[:current_user_id])
    if match.present?
      match.update(
        user2_accepted: true,
      )
    else
      Match.create(user1_id: params[:current_user_id], user2_id: params[:user_to_match_id])
    end

    head :ok
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/browses_helper.rb
module BrowsesHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/browses/browse.html.erb
<div class="container">
  <h1>Here, find your new croqueton :) </h1>
    <ul id="slides">
      <% @users.each do |user| %>
      <div class="slide " data-id="<%= user.id %>" data-current-user-id="<%=current_user.id%>">
        <div class="card_info">
          <span class="user_name_age"><%= user.first_name %>, 27</span>
          <span class="user_main_info"><i class="fa-solid fa-location-dot"></i> Location</span>
            <% user.photos.each do |photo| %>
              <li><%= cl_image_tag photo.key, height: 300, width: 300, crop: :thumb, gravity: :face %></li>
            <% end %>
        </div>
      </div>
      <% end %>
    </ul>
  <div class="slide-controls">
    <span id="dislike"><i class="fa-solid fa-circle-xmark fa-2x"></i></span>
    <span id="like"><i class="fa-solid fa-heart fa-2x"></i></span>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <span class="mb-3 mb-md-0 text-muted">© 2022 Company, Inc</span>
    </div>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
    </ul>
  </footer>
</div>

app/views/layouts/_nav.html.erb
  <div class="container">
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
        <span class="fs-4">Croquetons</span>
      </a>

      <ul class="nav nav-pills">
        <% if user_signed_in? %>
          <li class="nav-item"><a href="#" class="nav-link"> Hi <%= current_user.first_name %> ! </a></li>
          <%= link_to "Find a new croqueton", browse_path, class: "nav-link active" %>
          <%= link_to "My Matches", root_path, class: "nav-link" %>
          <%= link_to "Settings", edit_user_registration_path, class: "nav-link" %>
          <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
        <% else %>
          <%= link_to "About", about_path, class: "nav-link" %>
          <%= link_to "Features", about_path, class: "nav-link" %>
          <%= link_to "About", about_path, class: "nav-link" %>
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        <% end %>
  </ul>
    </header>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Croquetons</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%# NAVBAR %>
    <%= render "layouts/nav" %>

    <%# FLASHES %>
    <%= render "shared/flashes" %>

    <%= yield %>

    <%# FOOTER %>
    <%= render "layouts/footer" %>


  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

app/views/pages/home.html.erb
<div class="container">
  <div class="row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center rounded-3 border shadow-lg">
        <div class="col-lg-7 p-3 p-lg-5 pt-lg-3">
          <h1 class="display-4 fw-bold lh-1">Vamos <br> croquetons !! </h1>
          <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam accusantium labore ipsam nostrum ipsa nam necessitatibus accusamus harum amet placeat illo earum sunt voluptatem aliquid provident, quos autem libero doloremque.</p>
          <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4 mb-lg-3">
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg px-4 me-md-2 fw-bold" %>
            <%= link_to "Login", new_user_session_path, class: "btn btn-outline-secondary btn-lg px-4" %>
          </div>
        </div>
        <div class="col-lg-4 offset-lg-1 p-0 overflow-hidden shadow-lg">
          <%= image_tag "date_home_page.jpg", height: 300 %>
        </div>
  </div>

    <div class="row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center rounded-3 border shadow-lg">
        <div class="col-lg-7 p-3 p-lg-5 pt-lg-3">
          <h1 class="display-4 fw-bold lh-1">Vamos <br> croquetons !! </h1>
          <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam accusantium labore ipsam nostrum ipsa nam necessitatibus accusamus harum amet placeat illo earum sunt voluptatem aliquid provident, quos autem libero doloremque.</p>
          <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4 mb-lg-3">
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg px-4 me-md-2 fw-bold" %>
            <%= link_to "Login", new_user_session_path, class: "btn btn-outline-secondary btn-lg px-4" %>
          </div>
        </div>
        <div class="col-lg-4 offset-lg-1 p-0 overflow-hidden shadow-lg">
          <%= image_tag "date_home_page.jpg", height: 300 %>
        </div>
  </div>

  <div class="row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center rounded-3 border shadow-lg">
        <div class="col-lg-7 p-3 p-lg-5 pt-lg-3">
          <h1 class="display-4 fw-bold lh-1">Vamos <br> croquetons !! </h1>
          <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam accusantium labore ipsam nostrum ipsa nam necessitatibus accusamus harum amet placeat illo earum sunt voluptatem aliquid provident, quos autem libero doloremque.</p>
          <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4 mb-lg-3">
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg px-4 me-md-2 fw-bold" %>
            <%= link_to "Login", new_user_session_path, class: "btn btn-outline-secondary btn-lg px-4" %>
          </div>
        </div>
        <div class="col-lg-4 offset-lg-1 p-0 overflow-hidden shadow-lg">
          <%= image_tag "date_home_page.jpg", height: 300 %>
        </div>
  </div>


</div>

app/views/shared/_flashes.html.erb
<div class="container">
  <% if notice %>
    <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      <%= alert %>
    </div>
  <% end %>
</div>